apiVersion: v1
kind: Service
metadata:
  name: french-amortization-api-service
spec:
  ports:
    - protocol: "TCP"
      nodePort: 30000 # port that can be used to communicate externally with the service
      port: 80  # port that pods can internally use to communicate
      targetPort: 80  # the port that the service sends the request
  type: NodePort # Type of service
  selector:
    app: french-amortization-api